{ config, pkgs, lib, ... }:

{
  programs.tmux = {
    enable = true;
    prefix = "C-a";
    mouse = true;
    baseIndex = 1;
    historyLimit = 50000;
    terminal = "tmux-256color";
    escapeTime = 0;
    focusEvents = true;

    plugins = with pkgs.tmuxPlugins; [
      {
        plugin = resurrect;
        extraConfig = ''
          set -g @resurrect-capture-pane-contents 'on'
          set -g @resurrect-strategy-nvim 'session'
        '';
      }
      {
        plugin = continuum;
        extraConfig = ''
          set -g @continuum-restore 'on'
          set -g @continuum-save-interval '15'
        '';
      }
    ];

    extraConfig = ''
      # True color support
      set -ag terminal-overrides ",xterm-256color:RGB"

      # Pane base index
      setw -g pane-base-index 1

      # Renumber windows when one is closed
      set -g renumber-windows on

      # Reload config
      bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

      # Split panes using | and -
      bind | split-window -h -c "#{pane_current_path}"
      bind - split-window -v -c "#{pane_current_path}"
      unbind '"'
      unbind %

      # New window in current path
      bind c new-window -c "#{pane_current_path}"

      # Vim-style pane navigation
      bind -n C-h select-pane -L
      bind -n C-j select-pane -D
      bind -n C-k select-pane -U
      bind -n C-l select-pane -R

      # Resize panes with arrow keys
      bind -r Left resize-pane -L 5
      bind -r Down resize-pane -D 5
      bind -r Up resize-pane -U 5
      bind -r Right resize-pane -R 5

      # Quick window switching
      bind -n M-1 select-window -t 1
      bind -n M-2 select-window -t 2
      bind -n M-3 select-window -t 3
      bind -n M-4 select-window -t 4
      bind -n M-5 select-window -t 5

      # Status bar
      set -g status-position bottom
      set -g status-justify left
      set -g status-interval 1
      set -g status-left-length 50
      set -g status-right-length 50

      # Source theme colors (generated by wall-set script)
      if-shell "test -f ~/.config/tmux/theme.conf" "source-file ~/.config/tmux/theme.conf"

      # Fallback if theme file doesn't exist
      if-shell "test ! -f ~/.config/tmux/theme.conf" {
        set -g status-style "bg=#1e1e2e,fg=#cdd6f4"
        set -g pane-border-style "fg=#45475a"
        set -g pane-active-border-style "fg=#b4befe"
        set -g message-style "bg=#313244,fg=#cdd6f4"
        set -g status-left "#[bg=#89b4fa,fg=#1e1e2e,bold] #S #[bg=#1e1e2e] "
        set -g status-right "#[fg=#6c7086]%H:%M #[fg=#cdd6f4]%d-%m-%Y "
        setw -g window-status-format "#[fg=#6c7086] #I:#W "
        setw -g window-status-current-format "#[fg=#fab387,bold] #I:#W "
      }
    '';
  };
}
